<?php

/**
 * @file
 * Contains smartphones.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smartphones_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smartphones module.
    case 'help.page.smartphones':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function smartphones_theme() {
  $theme = [];
  $theme['smartphones_entity'] = [
    'render element' => 'elements',
    'file' => 'smartphones_entity.page.inc',
    'template' => 'smartphones_entity',
  ];
  $theme['smartphones_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'smartphones_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 
function smartphones_theme_suggestions_smartphones_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#smartphones_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'smartphones_entity__' . $sanitized_view_mode;
  $suggestions[] = 'smartphones_entity__' . $entity->bundle();
  $suggestions[] = 'smartphones_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'smartphones_entity__' . $entity->id();
  $suggestions[] = 'smartphones_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
*/